#  ____     ___ |    / _____ _____
# |  __    |    |___/    |     |
# |___| ___|    |    \ __|__   |     gsKit Open Source Project.
# ----------------------------------------------------------------------
# Copyright 2017 - Rick "Maximus32" Gaiser <rgaiser@gmail.com>
# Copyright 2004 - Chris "Neovanglist" Gilbert <Neovanglist@LainOS.org>
# Licenced under Academic Free License version 2.0
# Review gsKit README & LICENSE files for further details.
#
# examples/coverflow/Makefile - Makefile for "coverflow" example.
#

EE_BIN  = coverflow.elf
EE_OBJS = coverflow.o

include ../../Makefile.pref
include ../Makefile.global
