#  ____     ___ |    / _____ _____
# |  __    |    |___/    |     |
# |___| ___|    |    \ __|__   |     gsKit Open Source Project.
# ----------------------------------------------------------------------
# Copyright 2004 - Chris "Neovanglist" Gilbert <Neovanglist@LainOS.org>
# Licenced under Academic Free License version 2.0
# Review gsKit README & LICENSE files for further details.
#
# ee/gs/include/Makefile - gsKit include Makefile.
#

all:

clean:

install:
	mkdir -p $(GSKIT)/include
	cp *.h $(GSKIT)/include

include ../../../Makefile.global
include ../../../Makefile.pref
