#  ____     ___ |    / _____ _____
# |  __    |    |___/    |     |
# |___| ___|    |    \ __|__   |     gsKit Open Source Project.
# ----------------------------------------------------------------------
# Copyright 2020 -  Francisco Javier Trujillo Mata <fjtrujy@gmail.com>
# Licenced under Academic Free License version 2.0
# Review gsKit README & LICENSE files for further details.
#
# examples/modetesthires/Makefile - Makefile for "modetesthires" example.
#

EE_BIN  = modetesthires.elf
EE_OBJS = modetesthires.o pad.o
EE_LIBS_EXTRA = -lpad

include ../../Makefile.pref
include ../Makefile.global
