#  ____     ___ |    / _____ _____
# |  __    |    |___/    |     |
# |___| ___|    |    \ __|__   |     gsKit Open Source Project.
# ----------------------------------------------------------------------
# Copyright 2004 - Chris "Neovanglist" Gilbert <Neovanglist@LainOS.org>
# Licenced under Academic Free License version 2.0
# Review gsKit README & LICENSE files for further details.
#
# examples/Makefile - gsKit examples root makefile.
#

SUBDIRS =
SUBDIRS += alpha
SUBDIRS += basic
SUBDIRS += bigtex
SUBDIRS += coverflow
SUBDIRS += fb
SUBDIRS += font
SUBDIRS += fontm
SUBDIRS += hires
SUBDIRS += linuz-texture
SUBDIRS += modetest
SUBDIRS += pixelperfect
SUBDIRS += png-texture
SUBDIRS += texstream
SUBDIRS += textures
SUBDIRS += vsync

include ../Rules.make

