#  ____     ___ |    / _____ _____
# |  __    |    |___/    |     |
# |___| ___|    |    \ __|__   |     gsKit Open Source Project.
# ----------------------------------------------------------------------
# Copyright 2004 - Chris "Neovanglist" Gilbert <Neovanglist@LainOS.org>
# Licenced under Academic Free License version 2.0
# Review gsKit README & LICENSE files for further details.
#
# examples/linux-texture/Makefile - Example demonstrating CLUT texture operation.
#

EE_BIN  = texture.elf
EE_OBJS = texture.o testorig.o sample.o

include ../../Makefile.pref
include ../Makefile.global
